/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPracticeRouteImport } from './routes/_app/practice'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPracticeWritingTask2RouteImport } from './routes/_app/practice.writing-task2'
import { Route as AppPracticeWritingTask1RouteImport } from './routes/_app/practice.writing-task1'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeWritingTask2Route = AppPracticeWritingTask2RouteImport.update({
  id: '/writing-task2',
  path: '/writing-task2',
  getParentRoute: () => AppPracticeRoute,
} as any)
const AppPracticeWritingTask1Route = AppPracticeWritingTask1RouteImport.update({
  id: '/writing-task1',
  path: '/writing-task1',
  getParentRoute: () => AppPracticeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/practice': typeof AppPracticeRouteWithChildren
  '/practice/writing-task1': typeof AppPracticeWritingTask1Route
  '/practice/writing-task2': typeof AppPracticeWritingTask2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/practice': typeof AppPracticeRouteWithChildren
  '/practice/writing-task1': typeof AppPracticeWritingTask1Route
  '/practice/writing-task2': typeof AppPracticeWritingTask2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/practice': typeof AppPracticeRouteWithChildren
  '/_app/practice/writing-task1': typeof AppPracticeWritingTask1Route
  '/_app/practice/writing-task2': typeof AppPracticeWritingTask2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/practice'
    | '/practice/writing-task1'
    | '/practice/writing-task2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/practice'
    | '/practice/writing-task1'
    | '/practice/writing-task2'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/practice'
    | '/_app/practice/writing-task1'
    | '/_app/practice/writing-task2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/writing-task2': {
      id: '/_app/practice/writing-task2'
      path: '/writing-task2'
      fullPath: '/practice/writing-task2'
      preLoaderRoute: typeof AppPracticeWritingTask2RouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/practice/writing-task1': {
      id: '/_app/practice/writing-task1'
      path: '/writing-task1'
      fullPath: '/practice/writing-task1'
      preLoaderRoute: typeof AppPracticeWritingTask1RouteImport
      parentRoute: typeof AppPracticeRoute
    }
  }
}

interface AppPracticeRouteChildren {
  AppPracticeWritingTask1Route: typeof AppPracticeWritingTask1Route
  AppPracticeWritingTask2Route: typeof AppPracticeWritingTask2Route
}

const AppPracticeRouteChildren: AppPracticeRouteChildren = {
  AppPracticeWritingTask1Route: AppPracticeWritingTask1Route,
  AppPracticeWritingTask2Route: AppPracticeWritingTask2Route,
}

const AppPracticeRouteWithChildren = AppPracticeRoute._addFileChildren(
  AppPracticeRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPracticeRoute: typeof AppPracticeRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPracticeRoute: AppPracticeRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
